maintenance:
  cost: 20
  unpaid-limit: 2
  per-chunk-cost: 5
scoreboard:
  title: "§aContinent Server"
  minimap-size: 7
  show-coordinates: false
  refresh-interval: 0.5
server-address: "example.com"
colors:
  claimed: "§a"
  unclaimed: "§f"
symbols:
  center: "▣"
  chunk: "▩"
lobby-world: "lobby"
land-world: "world"
season:
  enabled: true
  durations:
    spring: 500
    summer: 700
    autumn: 400
    winter: 400
  particles:
    spring: 20
    summer: 15
    autumn: 25
    winter: 15
