name: continent
version: '1.0-SNAPSHOT'
main: me.continent.ContinentPlugin
api-version: '1.21'
commands:
  kingdom:
    description: Kingdom system command
    aliases: [k]
    usage: /kingdom <subcommand>
  gold:
    description: Gold system command
    usage: /gold <subcommand>
