name: continent
version: '1.0-SNAPSHOT'
main: me.continent.ContinentPlugin
api-version: '1.21'
commands:
  market:
    description: Player market
    usage: /market
  nation:
    description: Nation system command
    aliases: [n]
    usage: /nation <subcommand>
  gold:
    description: Gold system command
    usage: /gold <subcommand>
  war:
    description: War system command
    usage: /war <subcommand>
  guide:
    description: Provides guide books about kingdom, nation and war
    usage: /guide <topic>
  specialty:
    description: Specialty goods command
    usage: /specialty <subcommand>
  admin:
    description: Manage wars, economy and maintenance
    usage: /admin <subcommand>
  union:
    description: Manage unions of nations
    usage: /union <subcommand>
