name: continent
version: '1.0-SNAPSHOT'
main: me.continent.ContinentPlugin
api-version: '1.21'
commands:
  village:
    description: Village system command
    aliases: [v]
    usage: /village <subcommand>
  gold:
    description: Gold system command
    usage: /gold <subcommand>
  nation:
    description: nation system command
    aliases: [n]
    usage: /nation <subcommand>
  war:
    description: War system command
    usage: /war <subcommand>
  guide:
    description: Provides guide books about kingdom, village and war
    usage: /guide <topic>
  specialty:
    description: Specialty goods command
    usage: /specialty <subcommand>
  admin:
    description: Manage wars, economy and maintenance
    usage: /admin <subcommand>
