name: continent
version: '1.0-SNAPSHOT'
main: me.continent.ContinentPlugin
api-version: '1.21'
commands:
  village:
    description: Village system command
    aliases: [k]
    usage: /village <subcommand>
  gold:
    description: Gold system command
    usage: /gold <subcommand>
  kingdom:
    description: Kingdom system command
    aliases: [nation]
    usage: /kingdom <subcommand>
