name: continent
version: '1.0-SNAPSHOT'
main: me.continent.ContinentPlugin
api-version: '1.21'
commands:
  village:
    description: Village system command
    aliases: [k]
    usage: /village <subcommand>
  gold:
    description: Gold system command
    usage: /gold <subcommand>
  kingdom:
    description: Kingdom system command
    aliases: [nation]
    usage: /kingdom <subcommand>
  war:
    description: War system command
    usage: /war <subcommand>
  season:
    description: Season control command
    usage: /season <subcommand>
  seasonguide:
    description: Gives a guide book about the season system
    usage: /seasonguide
  guide:
    description: Provides guide books about kingdom, village and war
    usage: /guide <topic>
  specialty:
    description: Specialty goods command
    usage: /specialty <subcommand>
  admin:
    description: Manage wars, economy and maintenance
    usage: /admin <subcommand>
